application: mgouin
version: 16
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /powered-by-google-on-white\.png
  static_files: powered-by-google-on-white.png
  upload: powered-by-google-on-white\.png

- url: /gmls/?
  script: gmls.app

- url: /metar/?
  script: metar.app

- url: /.*
  script: mgouin.app

